version: '2'

services:

  composer:
    container_name: composer
    image: hyperledger/composer-playground
    ports:
      - '8080:8080'
    environment:
      COMPOSER_CONFIG: >
        {
          "defaultConnectionProfile": "hlfabric",
          "connectionProfiles": {
            "hlfabric": {
              "name": "hlfabric",
              "description": "Hyperledger Fabric v1.0",
              "type": "hlfv1",
              "keyValStore": "/home/composer/.composer-credentials",
              "timeout": 300,
              "orderers": [
                {
                  "url": "grpc://orderer.example.com:7050"
                }
              ],
              "channel": "composerchannel",
              "mspID": "Org1MSP",
              "ca": {
                "url": "http://ca.org1.example.com:7054",
                "name": "ca.org1.example.com"
              },
              "peers": [
                {
                  "requestURL": "grpc://peer0.org1.example.com:7051",
                  "eventURL": "grpc://peer0.org1.example.com:7053"
                }
              ]
            }
          },
          "credentials": {
            "hlfabric": {
              "PeerAdmin": "NOTUSED",
              "admin": "adminpw"
            }
          }
        }
networks:
  default:
    external:
      name: composer_default
