language: node_js
node_js:
    - '8'
matrix:
    include:
        - {}
        - env: DOCS=full FC_TASK=docs
        - env: SYSTEST=embedded,proxy,web FC_TASK=systest
#        - env: SYSTEST=hlfv1_tls FC_TASK=systest
        - env: SYSTEST=hlfv1-1_tls FC_TASK=systest
        - env: SYSTEST=hlfv1-2_tls FC_TASK=systest
        - env: SYSTEST=e2e FC_TASK=systest
dist: trusty
addons:
    apt:
        packages:
            - graphviz
before_install: |
    set -ev
    date
    ./.travis/before-install.sh
    date
install: |
    set -ev
    date
    ./.travis/install.sh
    date
script: ./.travis/script.sh
after_failure: |
    tail -n +1 -- /home/travis/.npm/_logs/*-debug.log
deploy:
    provider: script
    script: ./.travis/deploy.sh
    skip_cleanup: true
    on:
        all_branches: true
cache:
  directories:
    - node_modules
sudo: required
notifications:
  pushover:
    api_key: ayq7zvsxc641sfna65njkik1x9y25b
  webhooks:
    urls:
      - https://chat.hyperledger.org/hooks/BG3PeSerMSWRDSceE/GPCnCSqxMoyfqaTvLePSGudWjoCBwAcCT6bAKYRjK2sKSCM9
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
